ok 1 - shared = 0400 (faulty permission u-w)
ok 2 # skip shared=1 does not clear bits preset by umask 002 (missing POSIXPERM of POSIXPERM)
ok 3 # skip shared=1 does not clear bits preset by umask 022 (missing POSIXPERM of POSIXPERM)
ok 4 - shared=all
ok 5 # skip update-server-info honors core.sharedRepository (missing POSIXPERM of POSIXPERM)
ok 6 # skip shared = 0660 (r--r-----) ro (missing POSIXPERM of POSIXPERM)
ok 7 # skip shared = 0660 (rw-rw----) rw (missing POSIXPERM of POSIXPERM)
ok 8 # skip shared = 0640 (r--r-----) ro (missing POSIXPERM of POSIXPERM)
ok 9 # skip shared = 0640 (rw-r-----) rw (missing POSIXPERM of POSIXPERM)
ok 10 # skip shared = 0600 (r--------) ro (missing POSIXPERM of POSIXPERM)
ok 11 # skip shared = 0600 (rw-------) rw (missing POSIXPERM of POSIXPERM)
ok 12 # skip shared = 0666 (r--r--r--) ro (missing POSIXPERM of POSIXPERM)
ok 13 # skip shared = 0666 (rw-rw-rw-) rw (missing POSIXPERM of POSIXPERM)
ok 14 # skip shared = 0664 (r--r--r--) ro (missing POSIXPERM of POSIXPERM)
ok 15 # skip shared = 0664 (rw-rw-r--) rw (missing POSIXPERM of POSIXPERM)
ok 16 # skip git reflog expire honors core.sharedRepository (missing POSIXPERM of POSIXPERM)
ok 17 # skip forced modes (missing POSIXPERM of POSIXPERM)
# passed all 17 test(s)
1..17
