Your filesystem does not allow tabs in filenames
ok 1 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 2 # skip git ls-files no-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 3 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 4 # skip git ls-files with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 5 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 6 # skip git ls-files -z with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 7 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 8 # skip git ls-tree with funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 9 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 10 # skip git diff-index with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 11 # skip git diff-tree with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 12 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 13 # skip git diff-index -z with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 14 # skip git diff-tree -z with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 15 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 16 # skip git diff-tree -C with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 17 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 18 # skip git diff-tree delete with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 19 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 20 # skip git diff-tree delete with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 21 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 22 # skip git diff-tree delete with-funny (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 23 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 24 # skip git diff-tree rename with-funny applied (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 25 # skip setup expect (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 26 # skip git diff-tree delete with-funny applied (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
ok 27 # skip git apply non-git diff (missing TABS_IN_FILENAMES of TABS_IN_FILENAMES)
# passed all 27 test(s)
1..27
