ok 1 # skip create a commit where dir a/b changed to symlink (missing SYMLINKS of SYMLINKS)
ok 2 # skip keep a/b-2/c/d across checkout (missing SYMLINKS of SYMLINKS)
ok 3 # skip checkout should not have deleted a/b-2/c/d (missing SYMLINKS of SYMLINKS)
ok 4 # skip setup for merge test (missing SYMLINKS of SYMLINKS)
ok 5 # skip Handle D/F conflict, do not lose a/b-2/c/d in merge (resolve) (missing SYMLINKS of SYMLINKS)
ok 6 # skip Handle D/F conflict, do not lose a/b-2/c/d in merge (recursive) (missing SYMLINKS of SYMLINKS)
ok 7 # skip Handle F/D conflict, do not lose a/b-2/c/d in merge (resolve) (missing SYMLINKS of SYMLINKS)
ok 8 # skip Handle F/D conflict, do not lose a/b-2/c/d in merge (recursive) (missing SYMLINKS of SYMLINKS)
ok 9 # skip do not lose untracked in merge (resolve) (missing SYMLINKS of SYMLINKS)
ok 10 # skip do not lose untracked in merge (recursive) (missing SYMLINKS of SYMLINKS)
ok 11 # skip do not lose modifications in merge (resolve) (missing SYMLINKS of SYMLINKS)
ok 12 # skip do not lose modifications in merge (recursive) (missing SYMLINKS of SYMLINKS)
ok 13 # skip setup a merge where dir a/b-2 changed to symlink (missing SYMLINKS of SYMLINKS)
ok 14 # skip merge should not have D/F conflicts (resolve) (missing SYMLINKS of SYMLINKS)
ok 15 # skip merge should not have D/F conflicts (recursive) (missing SYMLINKS of SYMLINKS)
ok 16 # skip merge should not have F/D conflicts (recursive) (missing SYMLINKS of SYMLINKS)
# passed all 16 test(s)
1..16
